import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";

export default function (pi: ExtensionAPI) {
  pi.registerProvider("together", {
    baseUrl: "https://api.together.xyz/v1",
    apiKey: "TOGETHER_API_KEY",
    api: "openai-completions",
    models: [
      // Llama 4
      {
        id: "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8",
        name: "Llama 4 Maverick 17B",
        reasoning: false,
        input: ["text", "image"],
        cost: { input: 0.27, output: 0.85, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 1048576,
        maxTokens: 65536,
      },
      {
        id: "meta-llama/Llama-4-Scout-17B-16E-Instruct",
        name: "Llama 4 Scout 17B",
        reasoning: false,
        input: ["text", "image"],
        cost: { input: 0.18, output: 0.59, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 1048576,
        maxTokens: 65536,
      },
      // Llama 3.x
      {
        id: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        name: "Llama 3.3 70B Turbo",
        reasoning: false,
        input: ["text"],
        cost: { input: 0.88, output: 0.88, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 131072,
        maxTokens: 16384,
      },
      {
        id: "meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo",
        name: "Llama 3.1 405B Turbo",
        reasoning: false,
        input: ["text"],
        cost: { input: 3.5, output: 3.5, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 130000,
        maxTokens: 16384,
      },
      {
        id: "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo",
        name: "Llama 3.1 8B Turbo",
        reasoning: false,
        input: ["text"],
        cost: { input: 0.18, output: 0.18, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 131072,
        maxTokens: 16384,
      },
      // DeepSeek
      {
        id: "deepseek-ai/DeepSeek-R1",
        name: "DeepSeek R1",
        reasoning: true,
        input: ["text"],
        cost: { input: 3, output: 7, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 163839,
        maxTokens: 16384,
      },
      {
        id: "deepseek-ai/DeepSeek-R1-0528-tput",
        name: "DeepSeek R1 0528 (Throughput)",
        reasoning: true,
        input: ["text"],
        cost: { input: 3, output: 7, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 163839,
        maxTokens: 16384,
      },
      {
        id: "deepseek-ai/DeepSeek-V3.1",
        name: "DeepSeek V3.1",
        reasoning: false,
        input: ["text"],
        cost: { input: 0.6, output: 1.25, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 128000,
        maxTokens: 16384,
      },
      // Qwen
      {
        id: "Qwen/Qwen3-235B-A22B-Thinking-2507",
        name: "Qwen3 235B Thinking",
        reasoning: true,
        input: ["text"],
        cost: { input: 1.5, output: 1.5, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 262144,
        maxTokens: 32768,
      },
      {
        id: "Qwen/Qwen3-235B-A22B-Instruct-2507-tput",
        name: "Qwen3 235B Instruct",
        reasoning: false,
        input: ["text"],
        cost: { input: 1.5, output: 1.5, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 262144,
        maxTokens: 32768,
      },
      {
        id: "Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8",
        name: "Qwen3 Coder 480B",
        reasoning: false,
        input: ["text"],
        cost: { input: 2, output: 2, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 256000,
        maxTokens: 32768,
      },
      {
        id: "Qwen/Qwen3-Next-80B-A3B-Thinking",
        name: "Qwen3 Next 80B Thinking",
        reasoning: true,
        input: ["text"],
        cost: { input: 0.5, output: 0.5, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 262144,
        maxTokens: 32768,
      },
      {
        id: "Qwen/Qwen3-Next-80B-A3B-Instruct",
        name: "Qwen3 Next 80B Instruct",
        reasoning: false,
        input: ["text"],
        cost: { input: 0.5, output: 0.5, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 262144,
        maxTokens: 32768,
      },
      {
        id: "Qwen/Qwen2.5-72B-Instruct-Turbo",
        name: "Qwen 2.5 72B Turbo",
        reasoning: false,
        input: ["text"],
        cost: { input: 0.6, output: 0.6, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 32768,
        maxTokens: 8192,
      },
      {
        id: "Qwen/Qwen3-VL-32B-Instruct",
        name: "Qwen3 VL 32B",
        reasoning: false,
        input: ["text", "image"],
        cost: { input: 0.6, output: 0.6, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 256000,
        maxTokens: 16384,
      },
      // Kimi (Moonshot)
      {
        id: "moonshotai/Kimi-K2-Thinking",
        name: "Kimi K2 Thinking",
        reasoning: true,
        input: ["text"],
        cost: { input: 1.2, output: 4, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 262144,
        maxTokens: 32768,
      },
      {
        id: "moonshotai/Kimi-K2-Instruct-0905",
        name: "Kimi K2 Instruct",
        reasoning: false,
        input: ["text"],
        cost: { input: 0.6, output: 2, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 262144,
        maxTokens: 32768,
      },
      {
        id: "moonshotai/Kimi-K2.5",
        name: "Kimi K2.5",
        reasoning: true,
        input: ["text", "image"],
        cost: { input: 0.5, output: 2.8, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 262144,
        maxTokens: 32768,
      },
      // GLM
      {
        id: "zai-org/GLM-4.7",
        name: "GLM 4.7",
        reasoning: false,
        input: ["text"],
        cost: { input: 0.6, output: 0.6, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 202752,
        maxTokens: 16384,
      },
      // OpenAI OSS
      {
        id: "openai/gpt-oss-120b",
        name: "GPT OSS 120B",
        reasoning: false,
        input: ["text"],
        cost: { input: 0.15, output: 0.6, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 128000,
        maxTokens: 16384,
      },
      {
        id: "openai/gpt-oss-20b",
        name: "GPT OSS 20B",
        reasoning: false,
        input: ["text"],
        cost: { input: 0.06, output: 0.18, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 128000,
        maxTokens: 16384,
      },
      // Mistral
      {
        id: "mistralai/Ministral-3-14B-Instruct-2512",
        name: "Ministral 3 14B",
        reasoning: false,
        input: ["text"],
        cost: { input: 0.3, output: 0.3, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 262144,
        maxTokens: 16384,
      },
      {
        id: "mistralai/Mistral-Small-24B-Instruct-2501",
        name: "Mistral Small 24B",
        reasoning: false,
        input: ["text"],
        cost: { input: 0.8, output: 0.8, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 32768,
        maxTokens: 8192,
      },
      // Cogito (Deep Reasoning)
      {
        id: "deepcogito/cogito-v2-preview-llama-405B",
        name: "Cogito v2 Llama 405B",
        reasoning: true,
        input: ["text"],
        cost: { input: 5, output: 5, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 32768,
        maxTokens: 8192,
      },
      {
        id: "deepcogito/cogito-v2-1-671b",
        name: "Cogito v2.1 671B",
        reasoning: true,
        input: ["text"],
        cost: { input: 3, output: 3, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 32768,
        maxTokens: 8192,
      },
      // NVIDIA
      {
        id: "nvidia/NVIDIA-Nemotron-Nano-9B-v2",
        name: "Nemotron Nano 9B v2",
        reasoning: false,
        input: ["text"],
        cost: { input: 0.15, output: 0.15, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 131072,
        maxTokens: 16384,
      },
    ],
  });
}
